# Generated by Django 4.2.14 on 2024-08-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название (рус.)')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Изображение')),
                ('description_short', models.TextField(blank=True, verbose_name='Короткое писнаие')),
                ('description_long', models.TextField(blank=True, verbose_name='Полное описнаие')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon', models.FloatField(verbose_name='Долгота')),
            ],
        ),
    ]
