# Generated by Django 4.2.14 on 2024-08-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_id',
            field=models.IntegerField(null=True, verbose_name='Id места'),
        ),
    ]
