# Generated by Django 4.2.14 on 2024-08-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Картинки'),
        ),
    ]
