# Generated by Django 4.2.14 on 2024-08-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.CharField(max_length=200, null=True, verbose_name='Id места'),
        ),
    ]
