# Generated by Django 4.2.14 on 2024-08-25 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_place_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['sequence_number']},
        ),
    ]
